definitions:
  dao.RecordOnePageReq:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      total_count:
        type: integer
    required:
    - page
    - pageSize
    type: object
  dao.RecordOneReq:
    properties:
      rtspUrl:
        type: string
    required:
    - rtspUrl
    type: object
  response.Response:
    properties:
      code:
        description: 响应码
        type: integer
      data:
        description: 响应数据
      msg:
        description: 响应消息
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 返回 server 相关信息，可以用于健康检查
      parameters:
      - description: you can set custom trace id in header
        in: header
        name: trace_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      - BasicAuth: []
      summary: 默认的 Ping 接口
      tags:
      - x
  /record/one:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: recordOneReq
        required: true
        schema:
          $ref: '#/definitions/dao.RecordOneReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 录制单个流
      tags:
      - stream one
  /record/one/page:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: recordOneReq
        required: true
        schema:
          $ref: '#/definitions/dao.RecordOnePageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 分页查询
      tags:
      - stream one
swagger: "2.0"
